# NUMPY

**Numpy** is a python library which stands for NUMerical PYthon. It is an open source library developed for numerical computations. This is the foundation on which almost all the power of Python's data science toolkit is built, and learning NumPy is the first step on any Python data scientist's journey.

### Installation
The numpy library comes pre installed on most Python interpreters but could also be manually installed using the pip command; 
> *pip install numpy* 
or 
> *pip3 install numpy*

### Uses of Numpy
* For working with arrays (1D, 2D, 3D etc) and data structures
* For performing mathematical operations like trigonometry, statistical measures, algebra and transformation operations.
* Helps with vectorization and speeds up compute time compared to other data structures like list

## Numpy Operations
Let’s take a look at some of the numpy operations and methods

In [1]:
import numpy as np

### Creating arrays (1D, 2D, 3D)

In [2]:
#Example of a 1D array, the .shape method is used to check array shape

array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [3]:
array1.shape

(5,)

In [4]:
array1 = np.array(range(10))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a copy of an array

In [5]:
array_copy = array1.copy()
array_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Example of a 2D array

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.shape)
array_2d

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#Example of a 3D array

array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(array_3d.shape)
array_3d

(1, 3, 3)


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### Trigonometric Functions

In [8]:
angles = np.array([0, 30, 45, 60, 90])

In [9]:
angles

array([ 0, 30, 45, 60, 90])

In [10]:
# convert angles to radians using numpy by multiplying angles with pi/180

radians = []
for angle in angles:
    radian = (np.pi/180) * angle
    radians.append(radian)
    
radians    

[0.0,
 0.5235987755982988,
 0.7853981633974483,
 1.0471975511965976,
 1.5707963267948966]

In [11]:
# find sine of the converted angles

sine = np.sin(radians)

In [12]:
# find cosine of the converted angles

cosine = np.cos(radians)

In [13]:
arcsine = np.arcsin(sine)
arcsine

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [14]:
arccos = np.arccos(cosine)
arccos

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

### Mathematical Operations

In [15]:
array1 = np.array(range(1, 7))
array2 = array1.copy()

In [16]:
# add two arrays up

array_sum = array1 + array2
array_sum

array([ 2,  4,  6,  8, 10, 12])

In [17]:
# add two arrays up

array_diff = array1 - array2
array_diff

array([0, 0, 0, 0, 0, 0])

In [18]:
array3 = np.append(array2, 9)
array3

array([1, 2, 3, 4, 5, 6, 9])

In [19]:
array_sum = array3 + array2
array_sum

ValueError: operands could not be broadcast together with shapes (7,) (6,) 

Notice the error above, an error pops up when trying to sum arrays with inconsistent shape

Other operations include;

* Linear algebra, matrix operations
* Indexing and Slicing
* Array manipulation
* Broadcasting
* String Functions
* Statistical Functions